# File validator1.toml

[parity]
chain = "spec.json"
base_path = "validator1"

[network]
port = 30301
#bootnodes = []

[rpc]
disable = false
port = 8541
interface = "local"
apis = ["web3","eth","net","personal","parity","parity_set","traces","rpc","parity_accounts"]

[websockets]
disable = true

[account]
password = ["validator1.pwd"]

[mining]
engine_signer = "0xcece984d7c0bc5523c8d86b4d389a4414e0804a9"
reseal_on_txs = "none"
force_sealing = true
